apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  selector:
    app: train-schedule
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 3
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: jdominguez/train-schedule:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
